### ISSUE TITLE
The application "DocDown.app" can't be opened

### ISSUE THREAD

**Issue by rccordell** [lowercasename/docdown#14]
I'm not sure what has happened, but I now get that message when I attempt to open DocDown on my Macbook. I am running OS 10.15.2—was it the Catalina update?

**Comment by lowercasename** [comment]
Hi! I've started looking into this and there are a number of issues which have emerged with Catalina which I'm currently looking into, so you'll have to bear with me!

**Comment by lowercasename** [comment]
Okay, sorry for the delay - see if the new release here works better for you! https://github.com/lowercasename/docdown/releases/tag/v0.4.0

**Comment by rccordell** [comment]
Unfortunately I'm still getting the same error: can't be opened.

❦ ❦ ❦

Ryan Cordell | Associate Professor of English | Northeastern University | r.cordell@northeastern.edu | rccordell@gmail.com | @ryancordell | http://ryancordell.org

**Comment by lowercasename** [comment]
Let's do some debugging! Could you:

- Right click on the DocDown app and click ‘Show Package Contents’
- In the folder that opens, go to Contents > MacOS
- Double-click the file in that folder called ‘DocDown’

A Terminal window should open. Could you copy whatever output appears in there and paste it for me here?

**Comment by rccordell** [comment]
When I double click that it opens in TextEdit. Tried to force it to open in terminal but it won't do it. I can navigate into the package from the terminal--is there a command I could use there to try to run DocDown?


❦ ❦ ❦

Ryan Cordell | Associate Professor of English | Northeastern University | r.cordell@northeastern.edu | rccordell@gmail.com | @ryancordell | http://ryancordell.org

**Comment by lowercasename** [comment]
Yes, try: `./DocDown`, and when you're done, if it hangs, hit Ctrl+C to quit the app.

**Comment by rccordell** [comment]
This gets me a "permission denied" message, though when I look at the file permissions I have read & write privileges...

❦ ❦ ❦

Ryan Cordell | Associate Professor of English | Northeastern University | r.cordell@northeastern.edu | rccordell@gmail.com | @ryancordell | http://ryancordell.org

**Comment by lowercasename** [comment]
It looks like your Mac's security preferences might be preventing you from opening DocDown. Try going into System Preferences > Security, and see if there's a message there about DocDown, or an option to allow opening apps from untrusted providers (I can't afford the fees for an Apple trusted certificate unfortunately!)

**Comment by lowercasename** [comment]
Also try right clicking on DocDown and then clicking 'Open', although if the machine has somehow managed to block DocDown from opening, that may not help.

**Comment by rccordell** [comment]
I've seen that security message before but it's not coming up now. Terminal says Permission Denied when I try to open the app from the command line, but nothing in security preferences. If I click on the app it opens in TextEdit. If I drag the app to the Terminal nothing happens. Not sure what to do next.

❦ ❦ ❦

Ryan Cordell | Associate Professor of English | Northeastern University | r.cordell@northeastern.edu | rccordell@gmail.com | @ryancordell | http://ryancordell.org

**Comment by alistairwilson** [comment]
Also following this thread due to same issue , have tried all of the above too, but getting same results as Ryan

**Comment by alistairwilson** [comment]
If I open a Terminal folder within Package Contents > MacOS and then type `sudo /.DocDown`, it prompts me for password - but says `/.DocDown: command not found`

**Comment by lowercasename** [comment]
Try without sudo? Was DocDown working for you before?


________________________________

**Comment by alistairwilson** [comment]
I had last version (0.3.2) working fine. Followed the update workflow and now not working. Also tried reinstalling 0.3.2 afterwards, but that's giving same error now

**Comment by alistairwilson** [comment]
If there's some way I can generate some useful debugging info to paste here, let me know 👍

**Comment by escottmitchell** [comment]
Same as @alistairwilson. Was working before the 0.4.0 install and now neither 0.4.0 nor 0.3.2 will open.

**Comment by lowercasename** [comment]
Okay, let's all try the new version (0.4.1)! I updated electron-builder, and it's working for me on a machine where 0.4.0 was outputting the same error.

**Comment by rccordell** [comment]
Still can't run it, unfortunately. In Terminal I get "permission denied."

❦ ❦ ❦

Ryan Cordell | Associate Professor of English | Northeastern University | r.cordell@northeastern.edu | rccordell@gmail.com | @ryancordell | http://ryancordell.org

**Comment by alistairwilson** [comment]
Same for me! Have tried right clicking and opening also, but no success

**Comment by lowercasename** [comment]
Okay, never surrender - I've just switched the .zip file in that release with a .dmg file, can y'all see if that one works?

**Comment by escottmitchell** [comment]
.zip worked for me after I bypassed the Security setting in Preferences. Can we all gift you a Developer Account/Certificate? Ha!

**Comment by rccordell** [comment]
WIth the DMG it's working--thank you so much! I agree, what do we need to do to fund your developer account?

❦ ❦ ❦

Ryan Cordell | Associate Professor of English | Northeastern University | r.cordell@northeastern.edu | rccordell@gmail.com | @ryancordell | http://ryancordell.org
