### ISSUE TITLE
Just a question: why "change the citation key format to [auth:lower][year]"?

### ISSUE THREAD

**Issue by Sigfried** [lowercasename/docdown#16]
I'm about to try docdown. It seems super cool. 

I'm just curious about why the citation key format needs to be changed. Is there something in DocDown that relies on that format?

Thanks!
s

**Comment by retorquere** [comment]
I mean... it is in Raphael's username here... 😉 (jk)

**Comment by lowercasename** [comment]
Haha, damn right!

No, as far as I can now remember, there’s no specific need for it - as long as the codes in the exported Zotero library match those in the document, Pandoc-citeproc should work it out. Rewriting the instructions is on a long todo list so I’ll make a note of that, thanks!

**Comment by Sigfried** [comment]
I was having some weird problem, as it turned out, with the long keys. I was inserting them in MacVim and the script just seems to give up 2/3 through the key. I did have one short one that worked ok. So, maybe there was a reason you decided on the short key format.

**Comment by lowercasename** [comment]
Interesting! I think I got that directive from another tutorial about Pandoc+Zotero, so maybe it's a long-held tradition...

With the long keys, I recommend you file an issue in [zotpick-applescript](https://github.com/davepwsmith/zotpick-applescript) - if I understand you right, that's possibly where the problem sits?
