### ISSUE TITLE
Live citations

### ISSUE THREAD

**Issue by tokeriis** [lowercasename/docdown#18]
I appreciate this nifty little utility, but I have a suggestion for improvement/option that could improve it further: that the citekeys were converted to scannable cites, which would appear "live" in Word with the Zotero plugin installed.

I am not a programmer, but the implementation seems quite simple, using [this](https://retorque.re/zotero-better-bibtex/exporting/pandoc/). 

1. Package the zotero.lua filter
2. Then in settings, provide an option button which inserts the filter in the pandoc export argument.

**Comment by lowercasename** [comment]
I'm going to look into this, it looks great!

**Comment by lowercasename** [comment]
And it's done! The [newest release](https://github.com/lowercasename/docdown/releases/tag/v0.6.0) has this functionality - enable 'Live citations mode' in the preferences. There's also some usage notes on the wiki for this.

**Comment by tokeriis** [comment]
This is amazing. 😊
