### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by lpburrows** [lowercasename/docdown#20]
Thanks so much for this really helpful tool! One issue for me: my dissertation has several images in it, which I have included in Ulysses and which come out looking fine when I export to Markdown alone, but which DocDown isn't rendering (though it is getting the captions). Any chance of adding image support? Thanks again!

**Comment by ghost** [comment]
When exporting from Ulysses, only online images will directly work with DocDown. For local images, you need to add the image path as markdown – see https://pandoc.org/MANUAL.html#images. For example:

`![This is the caption](/pathname/of/image.png)`

**Comment by lowercasename** [comment]
Thanks, @jcransom. It's a side effect of the fact that Markdown was intended for conversion into/compatibility with HTML, I suppose - so all the file paths need to be absolute.
