### ISSUE TITLE
Files not exporting

### ISSUE THREAD

**Issue by joshuadazas** [lowercasename/docdown#23]
Thank you for making this contribution to the OpenSource Community. Kudos to you!

I am trying to start using DocDown alongside Ulysses. I followed the steps on your blog and in the wiki here. However, I cannot get the program to write an actual file. I made a simple test doc in Ulysses, including only two citation keys from Zotero. I export it into markdown and then drag and drop it into DocDown. I get a notification that the file was successfully written in the specified folder, but I do not see the file when checking the folder multiple times. I tried reinstalling your app, reinstalling pandoc, and of course, restarting my computer. But the issue still goes on. Is there any chance you might take a look at this? 

Best regards, 

Josh.

**Comment by lowercasename** [comment]
This should now be working in the new version, please give it a try and see how you go: https://github.com/lowercasename/docdown/releases/tag/v0.5.0
