### ISSUE TITLE
Title case

### ISSUE THREAD

**Issue by ghost** [lowercasename/docdown#3]
I have a problem with DocDown. It seems to automatically change the characters in titles to `Title Case`. Can you think of a remedy? I checked my .csl thoroughly, everything is set to `Sentence case` there. Moreover, the CSL visual editor renders my bibliography correctly, in `Sentence case`.

**Comment by lowercasename** [comment]
Hi! Could you run the following command in Terminal and see if you get the same results as through DocDown? (If you haven't already, you will have to install Pandoc and pandoc-citeproc first).

```
pandoc -s --filter pandoc-citeproc --bibliography /path/to/Zotero/bibliography/file.bib --csl /path/to/csl/file.csl --reference-doc /path/to/reference/doc/file.doc -f markdown+smart+escaped_line_breaks -t docx -o /path/to/output/file.docx
```

If the results are the same, it suggests the problem lies with Pandoc. You should also see if that affects the output you're experiencing in https://github.com/lowercasename/docdown/issues/4.

**Comment by ghost** [comment]
Hmmm, I tried many times, but I cannot get **any** output file. I do have pandoc and I (re)installed pandoc-citeproc just to be sure. Unfortunately, I'm not familiar with all the Terminal and Pandoc magic.

> pandoc -s --filter pandoc-citeproc --bibliography /Users/jakub/test/bbt.bib --csl /Users/jakub/test/orient.csl --reference-doc /Users/jakub/test/reference.docx -f markdown+smart+escaped_line_breaks -t docx -o /Users/jakub/test/test.docx

**Comment by lowercasename** [comment]
I'm so sorry, I forgot the crucial thing, your input Markdown document!

```
pandoc /YOUR/MARKDOWN/DOCUMENT.md -s --filter pandoc-citeproc --bibliography /Users/jakub/test/bbt.bib --csl /Users/jakub/test/orient.csl --reference-doc /Users/jakub/test/reference.docx -f markdown+smart+escaped_line_breaks -t docx -o /Users/jakub/test/test.docx
```

**Comment by ghost** [comment]
You were right. With Terminal I get exactly the same result. I understand it is entirely a pandoc-related issue and Downdoc is fine. But if you have any thoughts, don't hesitate. Thank for your help and thank you for this very useful app.

**Comment by ghost** [comment]
Problem solved. One needs to specify the language in all non-English items to protect them from this imperialistic Anglo-Saxon titlecasing.

**Comment by lowercasename** [comment]
I think this is also solved in the commit that allows you to use a .json or .yaml bibliography file: https://github.com/lowercasename/docdown/commit/521285a4036391370937da1ec95d16bc73c09043
