### ISSUE TITLE
DocDown doesn't create an export file, although it does say one has been saved?

### ISSUE THREAD

**Issue by ymshulman** [lowercasename/docdown#36]
I rely on DocDown for Pandoc, since it makes things so easy... But when I went to try it for my latest paper, although it says a document has been created in my Downloads folder, nothing is there. Is DocDown working for others on OS Monterey (version 12.3)?

(Troubleshooting steps taken: reinstalled DocDown, restarted computer, checked settings to verify saved folder, Zotero bib file up to date and used just fine by Zettlr, CSL file selected, using a default Word reference file for now.)

**Comment by lowercasename** [comment]
This should now be working in the new version, please give it a try and see how you go: https://github.com/lowercasename/docdown/releases/tag/v0.5.0
