### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by ghost** [lowercasename/docdown#4]
Cyrillic characters are all omitted and Greek ones are converted into mathematical equations (correctly, but awkwardly). Do you know if there something I can do to prevent it?

**Comment by ghost** [comment]
After many attempts, I found out the source of the problem. One needs to turn OFF the option `Export unicode as plain-text latex commands` in `Settings` → `Better BibTeX` → `Export`.

I don't know much about LaTeX, but I have the impression that adding this line (or similar) `\usepackage[english,russian]{babel}` somewhere appropriate in the workflow would solve the issue as well.

**Comment by lowercasename** [comment]
This is presumably solved by allowing .json and .yaml files in this commit: https://github.com/lowercasename/docdown/commit/521285a4036391370937da1ec95d16bc73c09043
