### ISSUE TITLE
Ulysses and paragraph breaks

### ISSUE THREAD

**Issue by JenFau** [lowercasename/docdown#40]
Using Ulysses, converted text using DocDown is not respecting the paragraph breaks and documents come out as one long paragraph. I know that I could put an extra paragraph break between paragraphs, but this doesn't work for numbered lists. How can I address this, please?

**Comment by lowercasename** [comment]
The standard Markdown syntax, which Pandoc and therefore DocDown follows, is that paragraphs have to be separated form each other by two paragraph breaks. I don't think there's a way to override that. What do you mean about numbered lists? Something like the following should work:

```
A paragraph.

A second paragraph.
Still part of the second paragraph.
As is this.

A numbered list:

1. One
2. Two
3. Three
```
