### ISSUE TITLE
[Feature request] Output to be saved in same folder as md file

### ISSUE THREAD

**Issue by carljoseph** [lowercasename/docdown#42]
I'm often working on numerous different documents and project, each one in their own folder. Would love the ability for docdown to save its output in the same folder as the .md file I drag in to convert.

e.g., 
```
/ProjectA/a.md
/ProjectA/a.docx (output)
/ProjectB/b.md
/ProjectB/b.docx
```

**Comment by carl-zen** [comment]
Is anyone maintaining this project?

**Comment by lowercasename** [comment]
Hi, I sure am! I recently made an update with some other requested features. Unfortunately I have little spare time, so I'll be able to look into this when I have a spare day or so. Otherwise you're very welcome to implement this yourself if you've got the technical skills! ☺️

**Comment by carljoseph** [comment]
Awesome. Thanks for clarifying :)

**Comment by lowercasename** [comment]
This is now an option in the [latest release](https://github.com/lowercasename/docdown/releases/tag/v0.7.1)!
