### ISSUE TITLE
No longer hidden from Dock

### ISSUE THREAD

**Issue by dantveita** [lowercasename/docdown#45]
DocDown used to only be visible in the menubar. After latest update, it also appears in the Dock. Im not sure if this is a new feature, or (hopefully) a bug. 

Using the latest version of both DocDown and MacOs.

**Comment by lowercasename** [comment]
This is definitely a bug! Will try and have a look at this soon, thanks for raising it.

**Comment by lowercasename** [comment]
This should be fixed in the [latest release](https://github.com/lowercasename/docdown/releases/tag/v0.7.2)!
