### ISSUE TITLE
question about using pandoc filters

### ISSUE THREAD

**Issue by lnrdgrnt** [lowercasename/docdown#48]
Is there a way to use Pandoc filters with DocDown? 

I would like to use pandoc-secnos so that I can refer to sections within the document and not worry if I change the order or the numbering of the chapters.

I wondered if this is possible?

**Comment by lowercasename** [comment]
There isn't an easy way to do that, and I don't envisage DocDown as a full wrapper UI for Pandoc, just a simple converter. For advanced use cases, the command line is probably the way forward!
