### ISSUE TITLE
Using CSL-JSON or CSL-YAML rather than BibTeX

### ISSUE THREAD

**Issue by retorquere** [lowercasename/docdown#5]
Hi, I'd recommend using CSL-JSON or CSL-YAML rather than BibTeX in the DocDown workflow to prevent one non-required (and lossy) translation between Zotero and the pandoc citation processor; for more details, see https://github.com/retorquere/zotero-better-bibtex/issues/1192#issuecomment-495498650.

**Comment by ghost** [comment]
Hi @lowercasename. I want to add that In my case switching to CSL-JSON helped indeed (thank you, @retorquere). All the issues I had before are gone. However, I had to return to your original Automator application. It would be great if your DocDown allowed .json in addition to .bib and I could keep using it.

**Comment by lowercasename** [comment]
Thank you so much both! I've now updated DocDown to allow .json and .yaml files - and have updated the readme to suggest that those are the way to go!

**Comment by retorquere** [comment]
I do want to note here that zotero by default doesn't export yaml files, and its csl-json files don't have citekeys - the yaml/json files we were talking about require having the BBT plugin installed.

**Comment by lowercasename** [comment]
Thanks for pointing that out - the tutorial that goes along with DocDown points out that BBT is pretty much an essential part of the process, and people who aren’t following the tutorial will hopefully know what they’re doing (or find the tutorial...).

**Comment by retorquere** [comment]
Fair enough -- I was thinking about the README which says

> A Zotero .json (recommended), .yaml (recommended)

which may suggest to new users that stock-Zotero could generate these.

**Comment by lowercasename** [comment]
I've now fixed this in the readme! :)
