### ISSUE TITLE
DocDown inserting hidden bookmarks in document?

### ISSUE THREAD

**Issue by skotzko** [lowercasename/docdown#50]
I noticed that DocDown is creating what I think are Word bookmarks (these grey brackets) around all the sections in the document. I'm not sure how to get rid of them. They aren't in my markdown file. 

<img width="159" alt="Screen Shot 2024-02-12 at 17 15 34" src="https://github.com/lowercasename/docdown/assets/311226/1ca942f5-3014-42df-97f2-5b0de3bdcbc8">

**Comment by lowercasename** [comment]
Looks like this is a default Pandoc feature called `auto_identifiers`, although it isn't immediately apparent why it affects Word output documents. You can disable it easily, though - open the Preferences window, and at the bottom in 'Other options', update the Markdown extensions line to read `+smart+escaped_line_breaks-auto_identifiers`.

<img width="748" alt="Screenshot 2024-02-13 at 14 10 14" src="https://github.com/lowercasename/docdown/assets/1748384/950a2e74-b55a-407c-a39b-1e721ef6e88e">

**Comment by skotzko** [comment]
Aha! That worked, thank you
